### ISSUE TITLE
Support socket monitor

### ISSUE THREAD

**Issue by janckerchen** [rolftimmermans/zeromq-ng#16]

**Comment by rolftimmermans** [comment]
This is already supported by `socket.events`, see for example: https://github.com/rolftimmermans/zeromq-ng#class-zmqobserver

Is there anything you're missing?

**Comment by janckerchen** [comment]
observer is what I want,   I just searched "monitor" in doc to confirm monitor support.

"monitor" is a key words in zeromq context,  consider add it in doc some where.
