### ISSUE TITLE
sock.connect should return promise

### ISSUE THREAD

**Issue by janckerchen** [rolftimmermans/zeromq-ng#17]

**Comment by rolftimmermans** [comment]
Hey, thanks for reporting this. Just wondering, do you mean this as a technicality, or do you have a specific use case?

ZMQ connects only when necessary and abstracts away the actual connection. It's possible to start sending messages while the underlying connection is still in progress. Waiting on the connection to be completed does not necessarily improve a program...

**Comment by janckerchen** [comment]
You explained well.   my wrong understanding is  
```
sock.connect(endpoint).then(()=> sock.send(msg));
```

so as you point, the right way is 

```
sock.connect(endpoint);
sock.send(msg);
```
