### ISSUE TITLE
How to convert socket message to  event emitter mode?

### ISSUE THREAD

**Issue by janckerchen** [rolftimmermans/zeromq-ng#18]
How to convert socket message(not events) to  event emitter mode?

I know there is 'Compatibility layer for ZeroMQ.js 4', so  socket.on('message', cb) is still available.

But it's the right way in next generation? 

I use rxjs in project,  I want to convert socket to observable,  I tried this

```ts
Observable.create((observer) =>{
            while (!this.sock.closed) {                   <---------------stuck
                this.sock.receive().then(observer.next); 
            }
            return ()=> this.sock.close();
        }).subscriber(this.handleMessage.bind(this))
```

it seems  stuck  at  infinity loop.

`while` is zeromq code style, but not  nodejs async style.

**Comment by rolftimmermans** [comment]
To elegantly receive events you'll want to use `await`, because otherwise you'll create an infinite amount of promises. `then()` does not block the `while` loop, but `await` does.

There is `socket.events.emitter` that converts the Observer into event emitter mode and returns the event emitter. That's probably what you want. I am no yet 100% sure if it should be public API but I guess your use case proves that it should be.

So I guess your example could become:

```Observable.create(socket.events.emitter).subscriber(this.handleMessage.bind(this))```

**Comment by janckerchen** [comment]
socket.events  doesn't  emit  'message' event  in which I extract data. 

```ts
type Event = "connect" | "connectDelay" | "connectRetry" | "listening" |
  "bindError" | "accept" | "acceptError" | "close" | "closeError" |
  "disconnect" | "stop" | "unknown"
```

BTW, `socket.events.emitter` not included in  types  define,  I use typescript.

**Comment by janckerchen** [comment]
wrap socket to observable  is very handy in  rxjs programming.

**Comment by rolftimmermans** [comment]
Ah right. So you're looking to use an event mode for messages, not events. Somehow I missed that.

The following code should do what you want:

```
const {EventEmitter} = require("events")

const socket = ...
const emitter = new EventEmitter

const run = async () => {
  while (!socket.closed) {
    const [event, data] = await socket.receive()
    emitter.emit(event, data)
  }
}

run()
```

**Comment by rolftimmermans** [comment]
Also, just to add a warning: the event emitter mode for messages is one of the primary reasons for the API overhaul. It does not suite the ZMQ pattern very well. The main issue is that there's no way to gracefully detect any problems with receiving messages. You can't have receive timeouts; messages will be read from the ZMQ queue automatically so you cannot delay receiving a message if your application is busy, etc.

**Comment by rolftimmermans** [comment]
Closing this since the use case seems covered by the API; feel free to comment if you have any other suggestions!
