### ISSUE TITLE
Missing v59 download file (404 on zeromq-ng-v5.0.0-beta.9-node-v59-linux-x64.tar.gz)

### ISSUE THREAD

**Issue by alesrebec** [rolftimmermans/zeromq-ng#28]
It appears some other projects rely on the exact version of zeromq-ng.

Here's the main part of the error:

`Tried to download(404): https://github.com/rolftimmermans/zeromq-ng/releases/download/v5.0.0-beta.9/zeromq-ng-v5.0.0-beta.9-node-v59-linux-x64.tar.gz
`

The latest version in [releases](https://github.com/rolftimmermans/zeromq-ng/releases) is v57, the project is trying to download v59.
I looks like it was removed.
@rolftimmermans can you put the file back or at least reference version 57 to use the same name?

**Comment by rolftimmermans** [comment]
Module ABI v59 corresponds to Node 9. No releases have been made for Node 9 for this module yet. I will move to using NAPI versioning for this project soon, allowing it to work with Node 9 as well.

**Comment by rolftimmermans** [comment]
The blocking issue with `node-pre-gyp` has been solved and I've been able to incorporate the necessary changes. Beta 11 is installable and should work with Node 8/9/10. Thanks for your patience!
