### ISSUE TITLE
v5.0.0-beta.10 release , when can I  npm install it?

### ISSUE THREAD

**Issue by janckerchen** [rolftimmermans/zeromq-ng#29]

**Comment by rolftimmermans** [comment]
There is a blocking issue with node-pre-gyp that needs to be solved before I can release.

**Comment by zorro-fr24** [comment]
Hi @rolftimmermans, do you have a link for the node-pre-gyp issue?

**Comment by rolftimmermans** [comment]
The original comment describing the open issues is https://github.com/mapbox/node-pre-gyp/pull/345#issuecomment-379067786

It's now an open issue at https://github.com/mapbox/node-pre-gyp/issues/402

**Comment by rolftimmermans** [comment]
The upstream issue has been resolved and I've been able to incorporate the necessary changes.

Beta 11 prebuilt binaries should work with Node 8/10.

Thanks for your patience!
