### ISSUE TITLE
zeromq-ng/lib/binary/napi-v3/zeromq-ng.node file is missing in new version 11

### ISSUE THREAD

**Issue by DaveRingelnatz** [rolftimmermans/zeromq-ng#41]
Hi Rolf,

your zeromq-ng module is used within the iota-prom-exporter module (https://github.com/crholliday/iota-prom-exporter). And this module asks for the above mentioned file and crashes as it is not there in your newest build (version 11) and will not be created during the "npm install" process.

Version 11 looks like:

> zeromq-ng@5.0.0-beta.11 install /opt/prometheus/iota-prom-exporter/node_modules/zeromq-ng
> node-pre-gyp configure --verbose --build-latest-napi-version-only

In version 9 it is there:

> zeromq-ng@5.0.0-beta.9 install /opt/prometheus/iota-prom-exporter/node_modules/zeromq-ng
> node-pre-gyp install --fallback-to-build

> [zeromq-ng] Success: "/opt/prometheus/iota-prom-exporter/node_modules/zeromq-ng/lib/binary/zeromq-ng.node" is installed via remote

Is this intended or is this a bug?

Greetings Dave

**Comment by rolftimmermans** [comment]
Thanks for reporting @DaveRingelnatz! Which Node version are you installing this with? On which platform?

**Comment by DaveRingelnatz** [comment]
Platform is Ubuntu 18.04, Node version is 8.11.4, NPM is version 5.6.0.

**Comment by rolftimmermans** [comment]
Alright, thanks. I do believe there was something wrong with the install command in `package.json`. I have pushed beta 12 which hopefully solves this. Could you please report back if this works for you? Thanks!

**Comment by rolftimmermans** [comment]
Excellent, thanks!
