### ISSUE TITLE
Disconnection Event

### ISSUE THREAD

**Issue by junknown** [rolftimmermans/zeromq-ng#43]
Hi, in a router <- multi dealer environment , how can i know, on router side, which dealer is disconnected? the disconnect event is correctly sended but with no other information other than address. Thanks.

**Comment by junknown** [comment]
I noticed that 0mq, on the connect and disconnect event, expose the fd of underlying socket . Is it possibile to pull it in js event?

**Comment by rolftimmermans** [comment]
Retrieving the `fd` is possible with zmq, but I left it out from the API because I thought there's nothing you could do with it.

Of course, it's possible to correlate the `fd` of a connect and disconnect event. @junknown Would that solve your use case?

**Comment by rolftimmermans** [comment]
It seems related to https://github.com/zeromq/libzmq/issues/2306

**Comment by junknown** [comment]
It would be perfect!! As now, there's no way to know how many and which clients are actually connected

**Comment by rolftimmermans** [comment]
You can count the number of connected clients by incrementing on a connect event and decrementing on a disconnect event. There's no API change needed to keep track of the number of connected peers, you can do so already.

The fd gives you a way to link specific connect and disconnect events together, but the same peer may have a different fd the next time so it's not a very useful thing otherwise.

**Comment by junknown** [comment]
This is true, but If not all clients are equals and I want to know exactly which client is available I need to have something that identify the disconnect/timeout  socket. I know that fd can be reassigned but it is not an issue if I use it only to match connect/disconnect event

**Comment by rolftimmermans** [comment]
Alright, I'll see if I can add the `fd` property to the events when it makes sense.

**Comment by junknown** [comment]
Great! Thank you so much.

**Comment by rolftimmermans** [comment]
This has been implemented upstream as `ZMQ_ROUTER_NOTIFY`, but it is conditionally compiled only for DRAFT builds. We don't currently release DRAFT versions of the library, but you can compile this yourself with `npm install --build-from-source --zmq-draft` or `npm_config_build_from_source =true ZMQ_DRAFT=true yarn`. Then define the option:

```js
const {Router, Socket} = require("zeromq-ng")
Socket.defineOption(97 /* ZMQ_ROUTER_NOTIFY */, "Int32", "notify", {on: Router, values: [null, "connect" /* 1 */, "disconnect" /* 2 */, "both" /* 3 */]})
const sock = new Router({notify: "disconnect"})
```

According to the documentation: when enabled, the socket delivers a zero-length message (with routing-id as first frame) when a peer connects or disconnects (depending on your setting, of course).

**Comment by rolftimmermans** [comment]
I will close this for now, please feel free to comment if you have any questions!
