### ISSUE TITLE
Getting Error: Cannot find name 'TypedArray'.

### ISSUE THREAD

**Issue by abhijitparkhi1983** [rolftimmermans/zeromq-ng#45]
Hello team Zeromq-ng.

I am trying to use zeromq-ng node module in my TypeScript application.
When I install zeromq-ng using visual studios core terminal for my project (with command npm i zeromq-ng) and compile the project, the terminal gives following compilation error **TS2304 : Cannot find name 'TypedArray'**. 
The file for which we are getting this error is **..\node_modules\zeromq-ng\lib\index.d.ts** at line 28 with code  **export type Message = TypedArray | ArrayBuffer | string | null**.

If we go to definition for ArrayBuffer, it fetches the definition from path **C:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\lib.es2015.symbol.wellknown.d.ts**
In this file, we dont see any reference to **TypedArray**

TypeScript version for ***C:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript** is version 3.0.3

Because of this error, we are not able to try out Zeromq-ng library atall. An urgent help will be very very helpful.

**Comment by abhijitparkhi1983** [comment]
Thanks @rolftimmermans 
Please let me know when do u plan to release this fix ?

**Comment by affanshahid** [comment]
Stuck on this as well, I see that the fix has been implemented, but not yet released.

**Comment by abhijitparkhi1983** [comment]
Thanks @rolftimmermans
Please let me know when do u plan to release this fix ?

**Comment by abhijitparkhi1983** [comment]
Please let me know when do u plan to release this fix ?
