### ISSUE TITLE
Multiple await bind in same process

### ISSUE THREAD

**Issue by scott-stewart** [rolftimmermans/zeromq-ng#49]
It looks like the ability to have multiple "bind" calls in the same process space broke between Node 10.14.1 and 10.14.2. I'm speculating here: https://github.com/nodejs/node/pull/23689 and due to isolate->GetCurrentContext(), but have not yet proved that out.

Below is an example that doesn't do anything other than try to make to "bind" calls in the same process. Both binds resolve in Node <= 10.14.1, but at least for me the second "await bind" never resolves (regardless of order) on Node >= 10.14.2 (tested in 10.14.2, 10.15, 11.8).

```
const zmq = require("zeromq-ng");
let socketsBound = false;

async function run() {
  const xsub = new zmq.XSubscriber;
  await xsub.bind("tcp://127.0.0.1:49154");
  console.log("XSubscriber bound");

  const xpub = new zmq.XPublisher;
  xpub.verbose = true;
  await xpub.bind("tcp://*:49153");
  console.log('XPublisher bound');

  socketsBound = true;
}

setInterval(checkStatus, 500);
function checkStatus() {
  console.log('Sockets bound: ' + socketsBound.toString());
}

run()
```

**Comment by rolftimmermans** [comment]
I know this has been a while, but I believe this has been fixed as of beta 19.
