### ISSUE TITLE
Example publisher segfaults on Raspbian (node 10 & 11)

### ISSUE THREAD

**Issue by jorispz** [rolftimmermans/zeromq-ng#51]
Starting the example publisher from the README on a Raspberry Pi 3 running Raspbian results in an immediate and consistently reproducible segfault. This happens on both Node 10.15.1 and 11.10.0.

I've installed [segfault-handler](https://www.npmjs.com/package/segfault-handler) but unfortunately this only tells me `PID 952 received SIGSEGV for address: 0x0` without any further information or stacktrace.

This could be related to #47, but that issue seems to be restricted to node 11.

**Comment by jorispz** [comment]
FYI, the segfault occurs after the first message has been sent, and the code hits `while(!sock.closed)` for the second time

**Comment by rolftimmermans** [comment]
Thanks for your report. It's been a while, but I'd love to hear if this is fixed in the latest beta versions.

**Comment by rolftimmermans** [comment]
Development has moved back to https://github.com/zeromq/zeromq.js with lots of bug fixes since this report. Please open a new issue there if you still run into any problems!
