### ISSUE TITLE
Fatal runtime error on Nodejs V8.10.0

### ISSUE THREAD

**Issue by IhostVlad** [rolftimmermans/zeromq-ng#53]
Having all necessary prerequisites from [ReadMe documentation]( https://github.com/rolftimmermans/zeromq-ng/blob/9a61bd84546c58ca025796914dcfb7768608f019/README.md#installation): Node.js 8.6+ (requires N-API).  
Currently using nodejs v8.10.0 (>=8.6.0) and having following runtime error, and nothing works :
```
node-pre-gyp info This Node instance does not support builds for N-API version 3
node-pre-gyp info This Node instance does not support builds for N-API version 3
``` 

Npm install generates following node_module  `zeromq-ng` content:
```
├───lib
│   └───binary
│       └───napi-v3
├───script
└───src
    └───util
```

Most likely expected N-API with different version or something similar. How to fix it? NodeJS version `8.10.0` is required. Thanks in advance.

**Comment by rolftimmermans** [comment]
It turns out the N-API interface of Node 8 was not stable enough. New beta versions have been release for Node 10/12+, but it seems we can't reasonably support Node 8. So I'd have to refer you to the classic ZeroMQ.js bindings for that. Sorry!
