### ISSUE TITLE
Need example for ng-electron

### ISSUE THREAD

**Issue by suikamoko** [rolftimmermans/zeromq-ng#54]
I'm newbie using typescript, when I Execute (```npm run ng:serve:web```) [ng-electron](https://github.com/maximegris/angular-electron) and tsconfig.json set library esnext.asynciterable will throw error 

```
ERROR in ../node_modules/zeromq-ng/lib/index.d.ts:216:31 - error TS2314: Generic type 'AsyncIterator<T>' requires 1 type argument(s).

216     [Symbol.asyncIterator](): AsyncIterator<ReceiveType<this>, undefined>;
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/zeromq-ng/lib/index.d.ts:756:35 - error TS2314: Generic type 'AsyncIterator<T>' requires 1 type argument(s).

756         [Symbol.asyncIterator](): AsyncIterator<ReceiveType<this>, undefined>;
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rolftimmermans** [comment]
What is the TypeScript compiler version you are using?

The signature of `AsyncIterator` has changed since version 3.6, and we are using the most recent definition. So it might mean you need at least TypeScript 3.6+.

**Comment by rolftimmermans** [comment]
Development has moved back to https://github.com/zeromq/zeromq.js, please open an issue there if this is still unresolved for you!
