### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by iFreedive** [rolftimmermans/zeromq-ng#8]
Hi 

I am trying to install via npm install zeromq-nq and get the following error

15 error code E404
16 error 404 Not Found: zeromq-nq@latest

**Comment by iFreedive** [comment]
ah should be zeromq-ng no -nq, I copied it from the front page

**Comment by rolftimmermans** [comment]
Thanks, now fixed by bbe1009905811386ae17372a04fb09b45c447e53.
